# Generated by Django 3.0.7 on 2020-07-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedroom',
            new_name='Bedrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='bathroom',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
