# Generated by Django 3.0.7 on 2020-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200702_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Bedrooms',
            new_name='bedrooms',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(),
        ),
    ]
